# Template config for quick debugging

dump_dir: /juice5b/scr5b/tanishq/lingua-out/debug
name: "debug"
steps: 100
seed: 777

optim:
    lr: 3e-4
    warmup: 50
    lr_min_ratio: 0.000001
    clip: 10.0

distributed:
    fsdp_type: no_shard
    compile: false
    model_dtype: bf16

model:
    dim: 512
    n_layers: 4
    n_heads: 8

data:
    root_dir: /juice5/scr5/nlp/data/huggingface/lingua-data/
    sources:
        fineweb_edu_10bt_shuffled: 100.0
    batch_size: 8
    seq_len: 2048
    tokenizer:
        name: bytes

checkpoint:
    dump:
        every: 1000
    eval:
        every: 1000

logging:
    freq: 10

eval: null
