#python -m lingua.stool config=apps/main/configs/llama2_7B.yaml nodes=32 account=fair_amaia_cw_codegen qos=lowest
# dump_dir: !!!CHANGE_THIS!!!
dump_base: out
name: "llama_7B_8H200"
steps: 6000 # chinchilla optimal is roughly 2_136_230 steps
grad_acc_steps: 1
probe_freq: null

seed: 777
optim:
  lr: 1.0e-3
  weight_decay: 0.1
  warmup: 2000
  lr_min_ratio: 0.000001
  clip: 1.0

distributed:
  fsdp_type: full_shard
  dp_shard: 8
  dp_replicate: 1
  compile: true
  model_dtype: bf16
  matmul_allow_tf32: false
  selective_activation_checkpointing: false
  tp_size: 1

model:
  dim: 4096
  n_layers: 32
  n_heads: 32
  rope_theta: 100_000
  ffn_dim_multiplier: 1.0
  multiple_of: 256

data:
  root_dir: /juice5/scr5/nlp/data/huggingface/lingua-data/
  sources:
    fineweb_edu_10bt_shuffled: 100.0
  batch_size: 4
  prefetch_size: 1024
  seq_len: 2048
  n_views: 2
  load_async: true
  tokenizer:
    name: tiktoken
    path: /juice5/scr5/nlp/data/huggingface/lingua-data/llama_tokenizer/original/tokenizer.model

profiling:
  run: false

checkpoint:
  dump:
    every: 500
    keep: 1
  eval:
    every: 1000
    keep: 1
  async_save_mode: "shm"
  async_cleanup: true

logging:
  freq: 1
  wandb:
    project: lingua-tests
    name: llama_7B_8H200

async_eval_gpus: 1
eval:
  harness:
    tasks:
      - hellaswag
      - task: boolq
        dataset_kwargs:
          trust_remote_code: true
      - piqa
      - task: social_iqa
        dataset_kwargs:
          trust_remote_code: true
      - winogrande
      - openbookqa
      - arc_easy
      - arc_challenge
      - race
      - commonsense_qa
      # - coqa
      - copa
      - mmlu
      - mmlu_pro
      # - task: nq_open
      #   num_fewshot: 5
      # - triviaqa
      # - gsm8k
      # - bbh
  validation: null
  generator:
    max_tokens: 8192
    dtype: bf16
    show_progress: true
    reduce_generation_overhead: true

slurm:
  account: nlp
  partition: jag-standard
  ngpu: 1
  ncpu: 16
  constraint: "[48G|80G|141G]"
  mem: 128G
  time: 1440  # 24 hours
