# dump_dir: !!!CHANGE_THIS!!!
dump_base: out
name: llama_8H200_chinchilla
total_flops: 26.205e18
probe_freq: null
seed: 777
grad_acc_steps: 1

optim:
  lr: 3e-3
  weight_decay: 0.01
  warmup: 1000
  lr_min_ratio: 0.000001
  clip: 1.0

distributed:
  fsdp_type: no_shard
  dp_replicate: 8
  compile: true
  model_dtype: bf16
  matmul_allow_tf32: false
  selective_activation_checkpointing: false
  tp_size: 1

model:
  dim: 1536
  n_layers: 16
  n_heads: 48

data:
  root_dir: /juice5/scr5/nlp/data/huggingface/lingua-data/
  sources:
    fineweb_edu_shuffled: 100.0
  batch_size: 32
  prefetch_size: 1024
  seq_len: 2048
  n_views: 2
  load_async: true
  add_bos: true
  add_eos: true
  tokenizer:
    name: tiktoken
    path: /juice5/scr5/nlp/data/huggingface/lingua-data/tokenizers/r50k_base_tokenizer/0ea1e91bbb3a60f729a8dc8f777fd2fc07cd8df4

profiling:
  run: false

checkpoint:
  dump:
    every: 500
    keep: 1
  eval:
    every: 500
    keep: 1
  async_save_mode: "shm"
  async_cleanup: true

logging:
  freq: 1
  wandb:
    project: lingua-chinchilla-tests

async_eval_gpus: 1
eval:
  harness:
    tasks:
      - hellaswag
      - task: boolq
        dataset_kwargs:
          trust_remote_code: true
      - piqa
      - task: social_iqa
        dataset_kwargs:
          trust_remote_code: true
      - winogrande
      - openbookqa
      - arc_easy
      - arc_challenge
      - race
      - commonsense_qa
  validation: null
  generator:
    max_tokens: 16384
    dtype: bf16
    show_progress: true
    reduce_generation_overhead: true

# slurm is used for async eval
slurm:
  account: nlp
  partition: jag-standard
  ngpu: 1
  ncpu: 16
  constraint: "[48G|80G|141G]"
  mem: 64G
  time: 1440  # 24 hours

